{{#if cfg.chef_server.client_name ~}}
  client_name = "{{cfg.chef_server.client_name}}"
{{/if ~}}
{{#if cfg.chef_server.client_key_path ~}}
  client_key = "{{cfg.chef_server.client_key_path}}"
{{/if ~}}
{{#if cfg.ohai_json_file ~}}
  ohai_json_file = "{{cfg.ohai_json_file}}"
{{/if ~}}
{{#if cfg.converge_status_json_file ~}}
  converge_status_json_file = "{{cfg.converge_status_json_file}}"
{{/if ~}}
{{#if cfg.compliance_status_json_file ~}}
  compliance_status_json_file = "{{cfg.compliance_status_json_file}}"
{{/if ~}}

log_file = "{{cfg.log_file}}"
data_collector_token = "{{cfg.data_collector_token}}"
num_nodes = {{cfg.num_nodes}}
num_actions = {{cfg.num_actions}}
interval = {{cfg.interval}}
node_name_prefix = "{{cfg.node_name_prefix}}"
chef_environment = "{{cfg.chef_environment}}"
run_list = {{toToml cfg.run_list}}
sleep_duration = {{cfg.sleep_duration}}
download_cookbooks = "{{cfg.download_cookbooks}}"
api_get_requests = {{toToml cfg.api_get_requests}}
chef_version = "{{cfg.chef_version}}"
chef_server_creates_client_key = {{cfg.chef_server_creates_client_key}}
enable_reporting = {{cfg.enable_reporting}}
random_data = {{cfg.random_data}}
liveness_agent = {{cfg.liveness_agent}}

{{#if bind.automate ~}}
  data_collector_url = "{{cfg.data_collector.protocol}}://{{bind.automate.first.sys.ip}}:{{bind.automate.first.cfg.port}}/{{cfg.data_collector.path}}"
{{/if ~}}
{{#if cfg.data_collector.host ~}}
  data_collector_url = "{{cfg.data_collector.protocol}}://{{cfg.data_collector.host}}:{{cfg.data_collector.port}}/{{cfg.data_collector.path}}"
{{/if ~}}

{{#if bind.chef-server ~}}
  chef_server_url = "{{cfg.chef_server.protocol}}://{{bind.chef-server.first.sys.ip}}:{{bind.chef-server.first.cfg.port}}/organizations/{{cfg.chef_server.organization}}"
{{/if ~}}
{{#if cfg.chef_server.host ~}}
  chef_server_url = "{{cfg.chef_server.protocol}}://{{cfg.chef_server.host}}:{{cfg.chef_server.port}}/organizations/{{cfg.chef_server.organization}}"
{{/if ~}}
